/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:5755ad1f-7e4b-493f-80c4-10c9ca77d5b1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_rpKSUDbCm",
    "aws_user_pools_web_client_id": "3iqo60gdsrkuikkn5mrmebbvg1",
    "oauth": {}
};


export default awsmobile;
