/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:5755ad1f-7e4b-493f-80c4-10c9ca77d5b1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_rpKSUDbCm",
    "aws_user_pools_web_client_id": "3iqo60gdsrkuikkn5mrmebbvg1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ehojeqkfrveyhd7zz4x2fp5igu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2cr5vft6d5ajtmw5aupquk2hlq",
    "aws_user_files_s3_bucket": "foodstock-aji15753-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
